/-
  TPS — Proposed Targets for Erdos Problem #20
  Auto-generated by scripts/target-propose.py
  Date: 2026-02-15T05:06:00Z
  Status: STAGED (pending verification + review)

  DO NOT manually edit. Promote via: python3 scripts/target-propose.py --promote
-/

import SunflowerLean.ErdosProblem20

-- ============================================================================
-- PROPOSED TARGETS (awaiting promotion)
-- ============================================================================

/-- [TPS-proposed] Upper bound: any 1-uniform 3-SF-free family has at most 2 members.
    Known value: f(1,3) = 2. -/
def UniformBound_f1_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 1 → IsSunflowerFree family 3 → family.card ≤ 2

/-- [TPS-proposed] Upper bound: any 2-uniform 3-SF-free family has at most 4 members.
    Known value: f(2,3) = 4. -/
def UniformBound_f2_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 2 → IsSunflowerFree family 3 → family.card ≤ 4

/-- [TPS-proposed] Upper bound: any 3-uniform 3-SF-free family has at most 6 members.
    Known value: f(3,3) = 6. -/
def UniformBound_f3_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 3 → IsSunflowerFree family 3 → family.card ≤ 6

/-- [TPS-proposed] Upper bound: any 4-uniform 3-SF-free family has at most 9 members.
    Known value: f(4,3) = 9. -/
def UniformBound_f4_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 4 → IsSunflowerFree family 3 → family.card ≤ 9

/-- [TPS-proposed] Upper bound: any 5-uniform 3-SF-free family has at most 13 members.
    Known value: f(5,3) = 13. -/
def UniformBound_f5_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 5 → IsSunflowerFree family 3 → family.card ≤ 13

/-- [TPS-proposed] Upper bound: any 6-uniform 3-SF-free family has at most 20 members.
    Known value: f(6,3) = 20. -/
def UniformBound_f6_3 {α : Type*} [DecidableEq α] : Prop :=
  ∀ (family : Finset (Finset α)),
    IsUniform family 6 → IsSunflowerFree family 3 → family.card ≤ 20
