/-
  M3 (F6): the quadratic lower bound M3(l,2) ≥ (l−2)²/8 for all l ≥ 4,
  conditional on the orthogoval-pair existence hypothesis class
  (`OrthogovalExistence`; CIJSSS Theorem 2.2 provides every prime power
  — cited, not formalized — and `fanoOrthogovalPair` shows the class is
  non-vacuous). Route: Bertrand's postulate (mathlib) picks a prime q
  in ((l−2)/4, (l−2)/2]; the doubled pencil family (F5) gives an
  M3-admissible(2q+2, 2) family of 2(q²+q+1) members; the padding lemma
  below lifts it to l-uniform (each member padded with its own tagged
  fresh points, intersections unchanged); 2(q²+q+1) ≥ (l−2)²/8.

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.M3.Pencil
import Mathlib.NumberTheory.Bertrand

namespace M3

variable {α : Type*} [DecidableEq α]

/-- A member padded with `k` fresh points tagged by the member itself
    (so distinct members get disjoint pads). -/
def padSet (k : ℕ) (S : Finset α) : Finset (α ⊕ Finset α × Fin k) :=
  S.image Sum.inl ∪
    Finset.univ.image (fun j : Fin k => Sum.inr (S, j))

/-- The padded family. -/
def padFam (F : Finset (Finset α)) (k : ℕ) :
    Finset (Finset (α ⊕ Finset α × Fin k)) :=
  F.image (padSet k)

lemma mem_padSet {k : ℕ} {S : Finset α} {x : α ⊕ Finset α × Fin k} :
    x ∈ padSet k S ↔
      (∃ a ∈ S, Sum.inl a = x) ∨ (∃ j : Fin k, Sum.inr (S, j) = x) := by
  simp [padSet, Finset.mem_union, Finset.mem_image]

lemma padSet_card (k : ℕ) (S : Finset α) :
    (padSet k S).card = S.card + k := by
  have hinj2 : Function.Injective
      (fun j : Fin k => (Sum.inr (S, j) : α ⊕ Finset α × Fin k)) := by
    intro j j' h
    simpa using h
  have hdisj : Disjoint (S.image Sum.inl)
      (Finset.univ.image
        (fun j : Fin k => (Sum.inr (S, j) : α ⊕ Finset α × Fin k))) := by
    rw [Finset.disjoint_left]
    rintro x hx1 hx2
    obtain ⟨a, _, rfl⟩ := Finset.mem_image.mp hx1
    obtain ⟨j, _, hj⟩ := Finset.mem_image.mp hx2
    exact Sum.noConfusion hj
  rw [padSet, Finset.card_union_of_disjoint hdisj,
    Finset.card_image_of_injective _ Sum.inl_injective,
    Finset.card_image_of_injective _ hinj2, Finset.card_univ,
    Fintype.card_fin]

lemma padSet_inter {k : ℕ} {S T : Finset α} (hST : S ≠ T) :
    padSet k S ∩ padSet k T = (S ∩ T).image Sum.inl := by
  ext x
  simp only [Finset.mem_inter, mem_padSet, Finset.mem_image]
  constructor
  · rintro ⟨hS | hS, hT | hT⟩
    · obtain ⟨a, ha, rfl⟩ := hS
      obtain ⟨b, hb, hba⟩ := hT
      obtain rfl : b = a := Sum.inl_injective hba
      exact ⟨b, ⟨ha, hb⟩, rfl⟩
    · obtain ⟨a, _, rfl⟩ := hS
      obtain ⟨j, hj⟩ := hT
      exact absurd hj (by simp)
    · obtain ⟨j, rfl⟩ := hS
      obtain ⟨b, _, hba⟩ := hT
      exact absurd hba (by simp)
    · obtain ⟨j, rfl⟩ := hS
      obtain ⟨j', hj'⟩ := hT
      simp only [Sum.inr.injEq, Prod.mk.injEq] at hj'
      exact absurd hj'.1.symm hST
  · rintro ⟨a, ⟨ha, hb⟩, rfl⟩
    exact ⟨Or.inl ⟨a, ha, rfl⟩, Or.inl ⟨a, hb, rfl⟩⟩

lemma padSet_injective (k : ℕ) :
    Function.Injective (padSet (α := α) k) := by
  intro S T h
  ext a
  constructor
  · intro ha
    have : Sum.inl a ∈ padSet k T := by
      rw [← h]
      exact mem_padSet.mpr (Or.inl ⟨a, ha, rfl⟩)
    rcases mem_padSet.mp this with ⟨b, hb, hba⟩ | ⟨j, hj⟩
    · rwa [← Sum.inl_injective hba]
    · exact absurd hj (by simp)
  · intro ha
    have : Sum.inl a ∈ padSet k S := by
      rw [h]
      exact mem_padSet.mpr (Or.inl ⟨a, ha, rfl⟩)
    rcases mem_padSet.mp this with ⟨b, hb, hba⟩ | ⟨j, hj⟩
    · rwa [← Sum.inl_injective hba]
    · exact absurd hj (by simp)

/-- F6 padding lemma (paper's padding step): padding every member with
    its own `k` fresh points preserves admissibility and cardinality,
    raising uniformity from `l` to `l + k`. -/
theorem padFam_M3Admissible {F : Finset (Finset α)} {l t : ℕ} (k : ℕ)
    (hF : M3Admissible F l t) :
    M3Admissible (padFam F k) (l + k) t ∧ (padFam F k).card = F.card := by
  obtain ⟨hu, hc, hsf⟩ := hF
  have hmem : ∀ X ∈ padFam F k, ∃ S, S ∈ F ∧ padSet k S = X := by
    intro X hX
    obtain ⟨S, hS, hSX⟩ := Finset.mem_image.mp hX
    exact ⟨S, hS, hSX⟩
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · intro X hX
    obtain ⟨S, hSF, rfl⟩ := hmem X hX
    rw [padSet_card, hu S hSF]
  · intro X hX Y hY hXY
    obtain ⟨S, hSF, rfl⟩ := hmem X hX
    obtain ⟨T, hTF, rfl⟩ := hmem Y hY
    have hST : S ≠ T := fun h => hXY (by rw [h])
    rw [padSet_inter hST,
      Finset.card_image_of_injective _ Sum.inl_injective]
    exact hc S hSF T hTF hST
  · rintro H hH ⟨hcard, core, hcore⟩
    obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
    have hXm : X ∈ padFam F k := hH (by simp)
    have hYm : Y ∈ padFam F k := hH (by simp)
    have hZm : Z ∈ padFam F k := hH (by simp)
    obtain ⟨S, hSF, rfl⟩ := hmem X hXm
    obtain ⟨T, hTF, rfl⟩ := hmem Y hYm
    obtain ⟨W, hWF, rfl⟩ := hmem Z hZm
    have hST : S ≠ T := fun h => hXY (by rw [h])
    have hSW : S ≠ W := fun h => hXZ (by rw [h])
    have hTW : T ≠ W := fun h => hYZ (by rw [h])
    have eST : (S ∩ T).image Sum.inl = core := by
      rw [← padSet_inter hST]
      exact hcore _ _ (by simp) (by simp) hXY
    have eSW : (S ∩ W).image Sum.inl = core := by
      rw [← padSet_inter hSW]
      exact hcore _ _ (by simp) (by simp) hXZ
    have eTW : (T ∩ W).image Sum.inl = core := by
      rw [← padSet_inter hTW]
      exact hcore _ _ (by simp) (by simp) hYZ
    have h1 : S ∩ T = S ∩ W :=
      Finset.image_injective Sum.inl_injective (eST.trans eSW.symm)
    have h2 : S ∩ T = T ∩ W :=
      Finset.image_injective Sum.inl_injective (eST.trans eTW.symm)
    refine hsf {S, T, W} ?_ ⟨?_, S ∩ T, ?_⟩
    · intro V hV
      simp only [Finset.mem_insert, Finset.mem_singleton] at hV
      rcases hV with rfl | rfl | rfl <;> assumption
    · exact Finset.card_eq_three.mpr ⟨S, T, W, hST, hSW, hTW, rfl⟩
    · intro A B hA hB hAB
      simp only [Finset.mem_insert, Finset.mem_singleton] at hA hB
      rcases hA with rfl | rfl | rfl <;> rcases hB with rfl | rfl | rfl
      · exact absurd rfl hAB
      · rfl
      · exact h1.symm
      · rw [Finset.inter_comm]
      · exact absurd rfl hAB
      · exact h2.symm
      · rw [Finset.inter_comm]; exact h1.symm
      · rw [Finset.inter_comm]; exact h2.symm
      · exact absurd rfl hAB
  · exact Finset.card_image_of_injective _ (padSet_injective k)

/-- Any admissible family relabels onto a family of naturals. -/
lemma M3_to_nat {β : Type*} [DecidableEq β] {F : Finset (Finset β)}
    {l t : ℕ} (hF : M3Admissible F l t) :
    ∃ H : Finset (Finset ℕ), M3Admissible H l t ∧ H.card = F.card := by
  obtain ⟨f, hf⟩ := exists_injOn_fin
    (U := F.biUnion id) (n := (F.biUnion id).card + 1) (by omega) (by omega)
  have hg : Set.InjOn (fun b => (f b : ℕ)) (F.biUnion id) := by
    intro a ha b hb hab
    exact hf ha hb (Fin.val_injective hab)
  obtain ⟨hadm, hcard⟩ := M3Admissible_image hF hg
  exact ⟨_, hadm, hcard⟩

/-- The hypothesis class: an orthogoval pair exists at every prime
    order. CIJSSS Theorem 2.2 provides every prime power (cited, not
    formalized); `fanoOrthogovalPair` (F5d) shows non-vacuity. -/
def OrthogovalExistence : Prop :=
  ∀ q : ℕ, q.Prime → Nonempty (OrthogovalPair (Fin (q ^ 2 + q + 1)) q)

/-- F6: the quadratic lower bound `M3(l,2) ≥ (l−2)²/8` for every
    `l ≥ 4`, conditional on orthogoval existence. Paper Theorem 1.2,
    lower bound (unconditional-in-l form via Bertrand). -/
theorem M3_quadratic_lower (hex : OrthogovalExistence) {l : ℕ}
    (hl : 4 ≤ l) :
    ∃ H : Finset (Finset ℕ), M3Admissible H l 2 ∧
      (l - 2) ^ 2 / 8 ≤ H.card := by
  rcases lt_or_ge l 6 with hl6 | hl6
  · -- l = 4, 5: a single l-set suffices ((l−2)²/8 ≤ 1)
    refine ⟨{Finset.range l}, ⟨?_, ?_, ?_⟩, ?_⟩
    · intro S hS
      rw [Finset.mem_singleton] at hS
      rw [hS, Finset.card_range]
    · intro S hS T hT hST
      rw [Finset.mem_singleton] at hS hT
      exact absurd (hS.trans hT.symm) hST
    · rintro H hH ⟨hcard, _⟩
      have := Finset.card_le_card hH
      rw [Finset.card_singleton] at this
      omega
    · rw [Finset.card_singleton]
      interval_cases l <;> decide
  · -- l ≥ 6: Bertrand prime in ((l−2)/4, (l−2)/2]
    set n := (l - 2) / 4 with hn
    obtain ⟨q, hqp, hq1, hq2⟩ :=
      Nat.exists_prime_lt_and_le_two_mul n (by omega)
    have h2q := hqp.two_le
    obtain ⟨O⟩ := hex q hqp
    obtain ⟨H₀, hadm₀, hcard₀⟩ := doubled_pencilFam O (by omega)
    have hle : 2 * q + 2 ≤ l := by omega
    obtain ⟨hadmp, hcardp⟩ :=
      padFam_M3Admissible (l - (2 * q + 2)) hadm₀
    rw [show 2 * q + 2 + (l - (2 * q + 2)) = l from by omega] at hadmp
    obtain ⟨H, hadm, hcard⟩ := M3_to_nat hadmp
    refine ⟨H, hadm, ?_⟩
    rw [hcard, hcardp, hcard₀]
    have key : (l - 2) ^ 2 ≤ 16 * q ^ 2 := by
      have h1 : l - 2 ≤ 4 * n + 3 := by omega
      have h2 : n + 1 ≤ q := hq1
      calc (l - 2) ^ 2 ≤ (4 * n + 3) ^ 2 := Nat.pow_le_pow_left h1 2
        _ ≤ 16 * (n + 1) ^ 2 := by nlinarith
        _ ≤ 16 * q ^ 2 := by
            have := Nat.pow_le_pow_left h2 2
            omega
    calc (l - 2) ^ 2 / 8 ≤ 16 * q ^ 2 / 8 := Nat.div_le_div_right key
      _ = 2 * q ^ 2 := by
          rw [show 16 * q ^ 2 = 8 * (2 * q ^ 2) from by ring,
            Nat.mul_div_cancel_left _ (by norm_num)]
      _ ≤ 2 * (q ^ 2 + q + 1) := by nlinarith

end M3
