/-
  M1: the doubling lemma.

  Two disjoint copies of an intersecting, pairwise-capped, 3-sunflower-free
  family form a (no longer intersecting, but still) pairwise-capped,
  3-sunflower-free family of twice the size. Paper Lemma 2.4
  ("Three-sunflower-free set systems with bounded pairwise intersections");
  FORMALIZATION_PLAN_M3.md milestone M1.

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidate generated by Claude; acceptance criterion is
  `lake build` (kernel); committed only if sorry-free and verified.
-/

import SunflowerLean.M3.Defs

namespace M3

open Function

variable {α β : Type*} [DecidableEq α] [DecidableEq β]

/-- Push a family on `α` into the left summand of `α ⊕ β`. -/
def famInl (F : Finset (Finset α)) : Finset (Finset (α ⊕ β)) :=
  F.map (Finset.mapEmbedding (Embedding.inl)).toEmbedding

/-- Push a family on `β` into the right summand of `α ⊕ β`. -/
def famInr (G : Finset (Finset β)) : Finset (Finset (α ⊕ β)) :=
  G.map (Finset.mapEmbedding (Embedding.inr)).toEmbedding

/-- The doubled family: disjoint copies side by side. -/
def doubleFam (F : Finset (Finset α)) (G : Finset (Finset β)) :
    Finset (Finset (α ⊕ β)) :=
  famInl F ∪ famInr G

omit [DecidableEq α] [DecidableEq β] in
lemma mem_famInl {F : Finset (Finset α)} {X : Finset (α ⊕ β)} :
    X ∈ famInl (β := β) F ↔ ∃ S ∈ F, S.map Embedding.inl = X := by
  simp only [famInl, Finset.mem_map, RelEmbedding.coe_toEmbedding,
    Finset.mapEmbedding_apply]

omit [DecidableEq α] [DecidableEq β] in
lemma mem_famInr {G : Finset (Finset β)} {X : Finset (α ⊕ β)} :
    X ∈ famInr (α := α) G ↔ ∃ T ∈ G, T.map Embedding.inr = X := by
  simp only [famInr, Finset.mem_map, RelEmbedding.coe_toEmbedding,
    Finset.mapEmbedding_apply]

/-- A left-copy set and a right-copy set are disjoint. -/
lemma inl_inter_inr (S : Finset α) (T : Finset β) :
    (S.map (Embedding.inl : α ↪ α ⊕ β)) ∩ (T.map Embedding.inr) = ∅ := by
  ext x
  simp only [Finset.mem_inter, Finset.mem_map, Finset.notMem_empty, iff_false,
    not_and]
  rintro ⟨a, _, rfl⟩ ⟨b, _, h⟩
  simp only [Embedding.inl, Embedding.inr, Embedding.coeFn_mk] at h
  exact Sum.noConfusion h

/-- Sunflower-freeness transports to the left copy. -/
lemma isSunflowerFree_famInl {F : Finset (Finset α)}
    (hF : IsSunflowerFree F 3) : IsSunflowerFree (famInl (β := β) F) 3 := by
  rintro H hH ⟨hcard, core, hcore⟩
  obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
  have hXm : X ∈ famInl (β := β) F := hH (by simp)
  have hYm : Y ∈ famInl (β := β) F := hH (by simp)
  have hZm : Z ∈ famInl (β := β) F := hH (by simp)
  obtain ⟨A, hA, hAeq⟩ := mem_famInl.mp hXm
  obtain ⟨B, hB, hBeq⟩ := mem_famInl.mp hYm
  obtain ⟨C, hC, hCeq⟩ := mem_famInl.mp hZm
  subst hAeq; subst hBeq; subst hCeq
  have hAB : A ≠ B := fun h => hXY (by rw [h])
  have hAC : A ≠ C := fun h => hXZ (by rw [h])
  have hBC : B ≠ C := fun h => hYZ (by rw [h])
  have eAB : (A ∩ B).map (Embedding.inl : α ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hXY
  have eAC : (A ∩ C).map (Embedding.inl : α ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hXZ
  have eBC : (B ∩ C).map (Embedding.inl : α ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hYZ
  have h1 : A ∩ B = A ∩ C := Finset.map_injective _ (eAB.trans eAC.symm)
  have h2 : A ∩ B = B ∩ C := Finset.map_injective _ (eAB.trans eBC.symm)
  refine hF {A, B, C} ?_ ⟨?_, A ∩ B, ?_⟩
  · intro W hW
    simp only [Finset.mem_insert, Finset.mem_singleton] at hW
    rcases hW with rfl | rfl | rfl <;> assumption
  · exact Finset.card_eq_three.mpr ⟨A, B, C, hAB, hAC, hBC, rfl⟩
  · intro S T hS hT hST
    simp only [Finset.mem_insert, Finset.mem_singleton] at hS hT
    rcases hS with rfl | rfl | rfl <;> rcases hT with rfl | rfl | rfl
    · exact absurd rfl hST
    · rfl
    · exact h1.symm
    · rw [Finset.inter_comm]
    · exact absurd rfl hST
    · exact h2.symm
    · rw [Finset.inter_comm]; exact h1.symm
    · rw [Finset.inter_comm]; exact h2.symm
    · exact absurd rfl hST

/-- Sunflower-freeness transports to the right copy. -/
lemma isSunflowerFree_famInr {G : Finset (Finset β)}
    (hG : IsSunflowerFree G 3) : IsSunflowerFree (famInr (α := α) G) 3 := by
  rintro H hH ⟨hcard, core, hcore⟩
  obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
  have hXm : X ∈ famInr (α := α) G := hH (by simp)
  have hYm : Y ∈ famInr (α := α) G := hH (by simp)
  have hZm : Z ∈ famInr (α := α) G := hH (by simp)
  obtain ⟨A, hA, hAeq⟩ := mem_famInr.mp hXm
  obtain ⟨B, hB, hBeq⟩ := mem_famInr.mp hYm
  obtain ⟨C, hC, hCeq⟩ := mem_famInr.mp hZm
  subst hAeq; subst hBeq; subst hCeq
  have hAB : A ≠ B := fun h => hXY (by rw [h])
  have hAC : A ≠ C := fun h => hXZ (by rw [h])
  have hBC : B ≠ C := fun h => hYZ (by rw [h])
  have eAB : (A ∩ B).map (Embedding.inr : β ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hXY
  have eAC : (A ∩ C).map (Embedding.inr : β ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hXZ
  have eBC : (B ∩ C).map (Embedding.inr : β ↪ α ⊕ β) = core := by
    rw [Finset.map_inter]
    exact hcore _ _ (by simp) (by simp) hYZ
  have h1 : A ∩ B = A ∩ C := Finset.map_injective _ (eAB.trans eAC.symm)
  have h2 : A ∩ B = B ∩ C := Finset.map_injective _ (eAB.trans eBC.symm)
  refine hG {A, B, C} ?_ ⟨?_, A ∩ B, ?_⟩
  · intro W hW
    simp only [Finset.mem_insert, Finset.mem_singleton] at hW
    rcases hW with rfl | rfl | rfl <;> assumption
  · exact Finset.card_eq_three.mpr ⟨A, B, C, hAB, hAC, hBC, rfl⟩
  · intro S T hS hT hST
    simp only [Finset.mem_insert, Finset.mem_singleton] at hS hT
    rcases hS with rfl | rfl | rfl <;> rcases hT with rfl | rfl | rfl
    · exact absurd rfl hST
    · rfl
    · exact h1.symm
    · rw [Finset.inter_comm]
    · exact absurd rfl hST
    · exact h2.symm
    · rw [Finset.inter_comm]; exact h1.symm
    · rw [Finset.inter_comm]; exact h2.symm
    · exact absurd rfl hST

/-- A same-copy pair (left) and a cross-copy third set cannot share a
    common core: the within-pair core is nonempty (intersecting family),
    the cross core is empty. -/
lemma mixed_core_left {F : Finset (Finset α)} (hint : IsIntersectingFam F)
    {A B : Finset α} {T : Finset β} (hA : A ∈ F) (hB : B ∈ F) (hAB : A ≠ B)
    {core : Finset (α ⊕ β)}
    (h1 : (A.map Embedding.inl) ∩ (B.map Embedding.inl) = core)
    (h2 : (A.map Embedding.inl) ∩ (T.map Embedding.inr) = core) : False := by
  rw [← Finset.map_inter] at h1
  rw [inl_inter_inr] at h2
  have hne : ((A ∩ B).map (Embedding.inl : α ↪ α ⊕ β)).Nonempty :=
    Finset.Nonempty.map (hint A hA B hB hAB)
  rw [h1, ← h2] at hne
  exact Finset.not_nonempty_empty hne

/-- Same, with the pair in the right copy. -/
lemma mixed_core_right {G : Finset (Finset β)} (hint : IsIntersectingFam G)
    {A B : Finset β} {T : Finset α} (hA : A ∈ G) (hB : B ∈ G) (hAB : A ≠ B)
    {core : Finset (α ⊕ β)}
    (h1 : (A.map Embedding.inr) ∩ (B.map Embedding.inr) = core)
    (h2 : (T.map Embedding.inl) ∩ (A.map Embedding.inr) = core) : False := by
  rw [← Finset.map_inter] at h1
  rw [inl_inter_inr] at h2
  have hne : ((A ∩ B).map (Embedding.inr : β ↪ α ⊕ β)).Nonempty :=
    Finset.Nonempty.map (hint A hA B hB hAB)
  rw [h1, ← h2] at hne
  exact Finset.not_nonempty_empty hne

/-- M1, the doubling lemma: disjoint copies of two `I3`-admissible families
    form an `M3`-admissible family of total size. Paper Lemma 2.4. -/
theorem doubling (F : Finset (Finset α)) (G : Finset (Finset β)) (l t : ℕ)
    (hl : 0 < l) (hF : I3Admissible F l t) (hG : I3Admissible G l t) :
    M3Admissible (doubleFam F G) l t ∧
      (doubleFam F G).card = F.card + G.card := by
  obtain ⟨⟨hFu, hFc, hFsf⟩, hFint⟩ := hF
  obtain ⟨⟨hGu, hGc, hGsf⟩, hGint⟩ := hG
  have memD : ∀ X ∈ doubleFam F G,
      (∃ S ∈ F, S.map (Embedding.inl : α ↪ α ⊕ β) = X) ∨
      (∃ T ∈ G, T.map (Embedding.inr : β ↪ α ⊕ β) = X) := by
    intro X hX
    rcases Finset.mem_union.mp hX with h | h
    · exact Or.inl (mem_famInl.mp h)
    · exact Or.inr (mem_famInr.mp h)
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  -- uniformity
  · intro X hX
    rcases memD X hX with ⟨S, hS, rfl⟩ | ⟨T, hT, rfl⟩
    · rw [Finset.card_map]; exact hFu S hS
    · rw [Finset.card_map]; exact hGu T hT
  -- pairwise cap
  · intro X hX Y hY hXY
    rcases memD X hX with ⟨S, hS, rfl⟩ | ⟨S, hS, rfl⟩ <;>
      rcases memD Y hY with ⟨T, hT, rfl⟩ | ⟨T, hT, rfl⟩
    · have hST : S ≠ T := fun h => hXY (by rw [h])
      rw [← Finset.map_inter, Finset.card_map]
      exact hFc S hS T hT hST
    · rw [inl_inter_inr]; simp
    · rw [Finset.inter_comm, inl_inter_inr]; simp
    · have hST : S ≠ T := fun h => hXY (by rw [h])
      rw [← Finset.map_inter, Finset.card_map]
      exact hGc S hS T hT hST
  -- sunflower-freeness
  · rintro H hH ⟨hcard, core, hcore⟩
    obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
    have hXm := hH (show X ∈ ({X, Y, Z} : Finset (Finset (α ⊕ β))) by simp)
    have hYm := hH (show Y ∈ ({X, Y, Z} : Finset (Finset (α ⊕ β))) by simp)
    have hZm := hH (show Z ∈ ({X, Y, Z} : Finset (Finset (α ⊕ β))) by simp)
    have cXY : X ∩ Y = core := hcore X Y (by simp) (by simp) hXY
    have cXZ : X ∩ Z = core := hcore X Z (by simp) (by simp) hXZ
    have cYZ : Y ∩ Z = core := hcore Y Z (by simp) (by simp) hYZ
    rcases memD X hXm with ⟨A, hA, rfl⟩ | ⟨A, hA, rfl⟩ <;>
      rcases memD Y hYm with ⟨B, hB, rfl⟩ | ⟨B, hB, rfl⟩ <;>
        rcases memD Z hZm with ⟨C, hC, rfl⟩ | ⟨C, hC, rfl⟩
    -- LLL: lift to a sunflower in the left copy
    · refine isSunflowerFree_famInl (β := β) hFsf {_, _, _} ?_
        ⟨hcard, core, hcore⟩
      intro W hW
      simp only [Finset.mem_insert, Finset.mem_singleton] at hW
      rcases hW with rfl | rfl | rfl
      · exact mem_famInl.mpr ⟨A, hA, rfl⟩
      · exact mem_famInl.mpr ⟨B, hB, rfl⟩
      · exact mem_famInl.mpr ⟨C, hC, rfl⟩
    -- LLR: pair (A,B) left, C right
    · have hAB : A ≠ B := fun h => hXY (by rw [h])
      exact mixed_core_left hFint hA hB hAB cXY cXZ
    -- LRL: pair (A,C) left, B right
    · have hAC : A ≠ C := fun h => hXZ (by rw [h])
      exact mixed_core_left hFint hA hC hAC cXZ cXY
    -- LRR: pair (B,C) right, A left
    · have hBC : B ≠ C := fun h => hYZ (by rw [h])
      exact mixed_core_right hGint hB hC hBC cYZ cXY
    -- RLL: pair (B,C) left, A right
    · have hBC : B ≠ C := fun h => hYZ (by rw [h])
      rw [Finset.inter_comm] at cXY
      exact mixed_core_left hFint hB hC hBC cYZ cXY
    -- RLR: pair (A,C) right, B left
    · have hAC : A ≠ C := fun h => hXZ (by rw [h])
      rw [Finset.inter_comm] at cXY
      exact mixed_core_right hGint hA hC hAC cXZ cXY
    -- RRL: pair (A,B) right, C left
    · have hAB : A ≠ B := fun h => hXY (by rw [h])
      rw [Finset.inter_comm] at cXZ
      exact mixed_core_right hGint hA hB hAB cXY cXZ
    -- RRR: lift to a sunflower in the right copy
    · refine isSunflowerFree_famInr (α := α) hGsf {_, _, _} ?_
        ⟨hcard, core, hcore⟩
      intro W hW
      simp only [Finset.mem_insert, Finset.mem_singleton] at hW
      rcases hW with rfl | rfl | rfl
      · exact mem_famInr.mpr ⟨A, hA, rfl⟩
      · exact mem_famInr.mpr ⟨B, hB, rfl⟩
      · exact mem_famInr.mpr ⟨C, hC, rfl⟩
  -- cardinality
  · have hdisj : Disjoint (famInl (β := β) F) (famInr (α := α) G) := by
      rw [Finset.disjoint_left]
      rintro X hX hX'
      obtain ⟨S, hS, rfl⟩ := mem_famInl.mp hX
      obtain ⟨T, hT, hTeq⟩ := mem_famInr.mp hX'
      have hSne : S.Nonempty := Finset.card_pos.mp (by rw [hFu S hS]; exact hl)
      obtain ⟨a, ha⟩ := hSne
      have hmem : (Embedding.inl a : α ⊕ β) ∈ T.map Embedding.inr := by
        rw [hTeq]
        exact Finset.mem_map_of_mem _ ha
      obtain ⟨b, _, hb⟩ := Finset.mem_map.mp hmem
      simp only [Embedding.inl, Embedding.inr, Embedding.coeFn_mk] at hb
      exact Sum.noConfusion hb
    have hdf : doubleFam F G = famInl (β := β) F ∪ famInr (α := α) G := rfl
    have hcF : (famInl (β := β) F).card = F.card := Finset.card_map _
    have hcG : (famInr (α := α) G).card = G.card := Finset.card_map _
    rw [hdf, Finset.card_union_of_disjoint hdisj, hcF, hcG]

/-- Headline corollary in existence form: an intersecting admissible family
    of size `m` yields a doubled admissible family of size `2m`. -/
theorem M3_ge_two_I3 (F : Finset (Finset α)) (l t : ℕ) (hl : 0 < l)
    (hF : I3Admissible F l t) :
    ∃ H : Finset (Finset (α ⊕ α)), M3Admissible H l t ∧
      H.card = 2 * F.card := by
  obtain ⟨hadm, hcard⟩ := doubling F F l t hl hF hF
  exact ⟨doubleFam F F, hadm, by rw [hcard]; ring⟩

end M3
