/-
  M3 (F3): the link recursion. Paper Lemma 2.1.

  M3(l,0) <= 2; and conditionally, if every M3(l-1,t-1)-admissible family
  has at most B members, then every M3(l,t)-admissible family has at most
  2 + 2l*B members: a maximal disjoint subcollection has size <= 2 (three
  mutually disjoint members are an empty-core 3-sunflower), every other
  member passes through one of its <= 2l points, and the link at a point
  (erase the point from the members through it) is (l-1)-uniform,
  (t-1)-capped, and sunflower-free (re-adjoining the point lifts a
  sunflower). Corollary: M3(l,2) <= 4l^2 + 2 via the t=1 theorem (F2).

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.M3.T1Exact

namespace M3

variable {α : Type*} [DecidableEq α]

/-- F3, base case: at cap 0 all members are pairwise disjoint, so three
    of them would form an empty-core 3-sunflower. -/
theorem M3_card_le_t0 {F : Finset (Finset α)} {l : ℕ}
    (hF : M3Admissible F l 0) : F.card ≤ 2 := by
  obtain ⟨hu, hc, hsf⟩ := hF
  by_contra h
  push_neg at h
  obtain ⟨T, hTsub, hTcard⟩ : ∃ T ⊆ F, T.card = 3 :=
    Finset.exists_subset_card_eq (by omega)
  obtain ⟨A, B, C, hAB, hAC, hBC, rfl⟩ := Finset.card_eq_three.mp hTcard
  have hA : A ∈ F := hTsub (by simp)
  have hB : B ∈ F := hTsub (by simp)
  have hC : C ∈ F := hTsub (by simp)
  have hempty : ∀ {P Q : Finset α}, P ∈ F → Q ∈ F → P ≠ Q → P ∩ Q = ∅ := by
    intro P Q hP hQ hPQ
    have := hc P hP Q hQ hPQ
    exact Finset.card_eq_zero.mp (by omega)
  refine hsf {A, B, C} hTsub ⟨?_, ∅, ?_⟩
  · exact Finset.card_eq_three.mpr ⟨A, B, C, hAB, hAC, hBC, rfl⟩
  · intro S T' hS hT' hST
    simp only [Finset.mem_insert, Finset.mem_singleton] at hS hT'
    rcases hS with rfl | rfl | rfl <;> rcases hT' with rfl | rfl | rfl <;>
      first
        | exact absurd rfl hST
        | exact hempty (by assumption) (by assumption) hST

/-- erase commutes with intersection. -/
lemma erase_inter_erase (S T : Finset α) (x : α) :
    S.erase x ∩ T.erase x = (S ∩ T).erase x := by
  ext y
  simp only [Finset.mem_inter, Finset.mem_erase]
  tauto

/-- The link of `F` at `x`: the members through `x`, with `x` removed. -/
def link (F : Finset (Finset α)) (x : α) : Finset (Finset α) :=
  (F.filter (fun S => x ∈ S)).image (fun S => S.erase x)

/-- Erasing `x` is injective on the members through `x` (re-insert it). -/
lemma erase_injOn_through (F : Finset (Finset α)) (x : α) :
    Set.InjOn (fun S : Finset α => S.erase x)
      ↑(F.filter (fun S => x ∈ S)) := by
  intro S hS T hT h
  rw [Finset.mem_coe, Finset.mem_filter] at hS hT
  have h' : S.erase x = T.erase x := h
  have hS' : S = insert x (S.erase x) := (Finset.insert_erase hS.2).symm
  have hT' : T = insert x (T.erase x) := (Finset.insert_erase hT.2).symm
  rw [hS', hT', h']

/-- F3, link admissibility: the link at `x` is (l-1)-uniform,
    (t-1)-capped, and sunflower-free. -/
lemma link_admissible {F : Finset (Finset α)} {l t : ℕ}
    (hF : M3Admissible F l t) (x : α) :
    M3Admissible (link F x) (l - 1) (t - 1) := by
  obtain ⟨hu, hc, hsf⟩ := hF
  have hmem : ∀ X ∈ link F x, ∃ S, S ∈ F ∧ x ∈ S ∧ S.erase x = X := by
    intro X hX
    obtain ⟨S, hS, hSX⟩ := Finset.mem_image.mp hX
    obtain ⟨hSF, hxS⟩ := Finset.mem_filter.mp hS
    exact ⟨S, hSF, hxS, hSX⟩
  refine ⟨?_, ?_, ?_⟩
  · intro X hX
    obtain ⟨S, hSF, hxS, rfl⟩ := hmem X hX
    rw [Finset.card_erase_of_mem hxS, hu S hSF]
  · intro X hX Y hY hXY
    obtain ⟨S, hSF, hxS, rfl⟩ := hmem X hX
    obtain ⟨T, hTF, hxT, rfl⟩ := hmem Y hY
    have hST : S ≠ T := fun h => hXY (by rw [h])
    rw [erase_inter_erase,
      Finset.card_erase_of_mem (Finset.mem_inter.mpr ⟨hxS, hxT⟩)]
    have := hc S hSF T hTF hST
    omega
  · rintro H hH ⟨hcard, core, hcore⟩
    obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
    have hXm : X ∈ link F x := hH (by simp)
    have hYm : Y ∈ link F x := hH (by simp)
    have hZm : Z ∈ link F x := hH (by simp)
    obtain ⟨S, hSF, hxS, rfl⟩ := hmem X hXm
    obtain ⟨T, hTF, hxT, rfl⟩ := hmem Y hYm
    obtain ⟨W, hWF, hxW, rfl⟩ := hmem Z hZm
    have hST : S ≠ T := fun h => hXY (by rw [h])
    have hSW : S ≠ W := fun h => hXZ (by rw [h])
    have hTW : T ≠ W := fun h => hYZ (by rw [h])
    have key : ∀ {P Q : Finset α}, x ∈ P → x ∈ Q →
        P.erase x ∩ Q.erase x = core → P ∩ Q = insert x core := by
      intro P Q hxP hxQ hcoreeq
      rw [← hcoreeq, erase_inter_erase,
        Finset.insert_erase (Finset.mem_inter.mpr ⟨hxP, hxQ⟩)]
    have eST := key hxS hxT (hcore _ _ (by simp) (by simp) hXY)
    have eSW := key hxS hxW (hcore _ _ (by simp) (by simp) hXZ)
    have eTW := key hxT hxW (hcore _ _ (by simp) (by simp) hYZ)
    refine hsf {S, T, W} ?_ ⟨?_, insert x core, ?_⟩
    · intro V hV
      simp only [Finset.mem_insert, Finset.mem_singleton] at hV
      rcases hV with rfl | rfl | rfl <;> assumption
    · exact Finset.card_eq_three.mpr ⟨S, T, W, hST, hSW, hTW, rfl⟩
    · intro P Q hP hQ hPQ
      simp only [Finset.mem_insert, Finset.mem_singleton] at hP hQ
      rcases hP with rfl | rfl | rfl <;> rcases hQ with rfl | rfl | rfl
      · exact absurd rfl hPQ
      · exact eST
      · exact eSW
      · rw [Finset.inter_comm]; exact eST
      · exact absurd rfl hPQ
      · exact eTW
      · rw [Finset.inter_comm]; exact eSW
      · rw [Finset.inter_comm]; exact eTW
      · exact absurd rfl hPQ

/-- The members through a point are bounded by any bound on
    (l-1, t-1)-admissible families, via the link. -/
lemma card_through_le {F : Finset (Finset α)} {l t B : ℕ}
    (hF : M3Admissible F l t)
    (hB : ∀ G : Finset (Finset α), M3Admissible G (l - 1) (t - 1) →
      G.card ≤ B)
    (x : α) : (F.filter (fun S => x ∈ S)).card ≤ B := by
  rw [← Finset.card_image_of_injOn (erase_injOn_through F x)]
  exact hB _ (link_admissible hF x)

/-- F3, the recursion: if every (l-1, t-1)-admissible family on `α` has
    at most `B` members, every (l, t)-admissible family on `α` has at
    most `2 + 2l*B`. Paper Lemma 2.1. -/
theorem link_recursion {l t B : ℕ}
    (hB : ∀ G : Finset (Finset α), M3Admissible G (l - 1) (t - 1) →
      G.card ≤ B)
    {F : Finset (Finset α)} (hF : M3Admissible F l t) :
    F.card ≤ 2 + 2 * l * B := by
  obtain ⟨hu, hc, hsf⟩ := hF
  rcases F.eq_empty_or_nonempty with rfl | ⟨A1, hA1⟩
  · simp
  by_cases hdisj : ∃ A ∈ F, ∃ B' ∈ F, A ≠ B' ∧ A ∩ B' = ∅
  · -- a disjoint pair exists; everything else meets one of its 2l points
    obtain ⟨A, hA, B', hB', hAB, hABe⟩ := hdisj
    have hcover : F ⊆ {A, B'} ∪
        (A ∪ B').biUnion (fun x => F.filter (fun S => x ∈ S)) := by
      intro S hS
      rw [Finset.mem_union]
      by_cases hSA : S = A
      · left; simp [hSA]
      by_cases hSB : S = B'
      · left; simp [hSB]
      by_cases hmA : (S ∩ A).Nonempty
      · obtain ⟨x, hx⟩ := hmA
        obtain ⟨hxS, hxA⟩ := Finset.mem_inter.mp hx
        exact Or.inr (Finset.mem_biUnion.mpr ⟨x, Finset.mem_union_left _ hxA,
          Finset.mem_filter.mpr ⟨hS, hxS⟩⟩)
      by_cases hmB : (S ∩ B').Nonempty
      · obtain ⟨x, hx⟩ := hmB
        obtain ⟨hxS, hxB⟩ := Finset.mem_inter.mp hx
        exact Or.inr (Finset.mem_biUnion.mpr ⟨x, Finset.mem_union_right _ hxB,
          Finset.mem_filter.mpr ⟨hS, hxS⟩⟩)
      -- S disjoint from both: empty-core sunflower {A, B', S}
      exfalso
      rw [Finset.not_nonempty_iff_eq_empty] at hmA hmB
      refine hsf {A, B', S} ?_ ⟨?_, ∅, ?_⟩
      · intro W hW
        simp only [Finset.mem_insert, Finset.mem_singleton] at hW
        rcases hW with rfl | rfl | rfl <;> assumption
      · exact Finset.card_eq_three.mpr
          ⟨A, B', S, hAB, fun h => hSA h.symm, fun h => hSB h.symm, rfl⟩
      · intro P Q hP hQ hPQ
        simp only [Finset.mem_insert, Finset.mem_singleton] at hP hQ
        rcases hP with rfl | rfl | rfl <;> rcases hQ with rfl | rfl | rfl
        · exact absurd rfl hPQ
        · exact hABe
        · rw [Finset.inter_comm]; exact hmA
        · rw [Finset.inter_comm]; exact hABe
        · exact absurd rfl hPQ
        · rw [Finset.inter_comm]; exact hmB
        · exact hmA
        · exact hmB
        · exact absurd rfl hPQ
    have h1 : F.card ≤ ({A, B'} : Finset (Finset α)).card +
        ((A ∪ B').biUnion (fun x => F.filter (fun S => x ∈ S))).card :=
      le_trans (Finset.card_le_card hcover) (Finset.card_union_le _ _)
    have h2 : ({A, B'} : Finset (Finset α)).card ≤ 2 :=
      le_trans (Finset.card_insert_le _ _) (by simp)
    have h3 := Finset.card_biUnion_le
      (s := A ∪ B') (t := fun x => F.filter (fun S => x ∈ S))
    have h4 : ∑ x ∈ A ∪ B', (F.filter (fun S => x ∈ S)).card ≤
        (A ∪ B').card * B := by
      calc ∑ x ∈ A ∪ B', (F.filter (fun S => x ∈ S)).card
          ≤ ∑ _x ∈ A ∪ B', B :=
            Finset.sum_le_sum (fun x _ => card_through_le ⟨hu, hc, hsf⟩ hB x)
        _ = (A ∪ B').card * B := by rw [Finset.sum_const, smul_eq_mul]
    have h5 : (A ∪ B').card ≤ 2 * l := by
      have hle := Finset.card_union_le A B'
      rw [hu A hA, hu B' hB'] at hle
      omega
    have h6 : (A ∪ B').card * B ≤ 2 * l * B := Nat.mul_le_mul_right B h5
    calc F.card
        ≤ ({A, B'} : Finset (Finset α)).card +
          ((A ∪ B').biUnion (fun x => F.filter (fun S => x ∈ S))).card := h1
      _ ≤ 2 + (A ∪ B').card * B := Nat.add_le_add h2 (h3.trans h4)
      _ ≤ 2 + 2 * l * B := Nat.add_le_add_left h6 2
  · -- no disjoint pair: everything else meets A1, through its l points
    push_neg at hdisj
    have hcover : F ⊆ {A1} ∪
        A1.biUnion (fun x => F.filter (fun S => x ∈ S)) := by
      intro S hS
      rw [Finset.mem_union]
      by_cases hSA : S = A1
      · left; simp [hSA]
      obtain ⟨x, hx⟩ := hdisj S hS A1 hA1 hSA
      obtain ⟨hxS, hxA⟩ := Finset.mem_inter.mp hx
      exact Or.inr (Finset.mem_biUnion.mpr
        ⟨x, hxA, Finset.mem_filter.mpr ⟨hS, hxS⟩⟩)
    have h1 : F.card ≤ ({A1} : Finset (Finset α)).card +
        (A1.biUnion (fun x => F.filter (fun S => x ∈ S))).card :=
      le_trans (Finset.card_le_card hcover) (Finset.card_union_le _ _)
    have h3 := Finset.card_biUnion_le
      (s := A1) (t := fun x => F.filter (fun S => x ∈ S))
    have h4 : ∑ x ∈ A1, (F.filter (fun S => x ∈ S)).card ≤ A1.card * B := by
      calc ∑ x ∈ A1, (F.filter (fun S => x ∈ S)).card
          ≤ ∑ _x ∈ A1, B :=
            Finset.sum_le_sum (fun x _ => card_through_le ⟨hu, hc, hsf⟩ hB x)
        _ = A1.card * B := by rw [Finset.sum_const, smul_eq_mul]
    have h6 : A1.card * B ≤ 2 * l * B := by
      refine Nat.mul_le_mul_right B ?_
      rw [hu A1 hA1]
      omega
    calc F.card
        ≤ ({A1} : Finset (Finset α)).card +
          (A1.biUnion (fun x => F.filter (fun S => x ∈ S))).card := h1
      _ ≤ 1 + A1.card * B := Nat.add_le_add (by simp) (h3.trans h4)
      _ ≤ 2 + 2 * l * B := Nat.add_le_add (by norm_num) h6

/-- F3, corollary: `M3(l,2) ≤ 4l² + 2`, from the recursion and the t=1
    theorem (F2). Paper Corollary of Lemma 2.1 + Theorem 1.1. -/
theorem M3_card_le_t2 {F : Finset (Finset α)} {l : ℕ}
    (hF : M3Admissible F l 2) : F.card ≤ 4 * l ^ 2 + 2 := by
  have hB : ∀ G : Finset (Finset α), M3Admissible G (l - 1) (2 - 1) →
      G.card ≤ 2 * (l - 1) + 2 := fun G hG => M3_card_le_t1 hG
  have h := link_recursion hB hF
  have h2 : 2 + 2 * l * (2 * (l - 1) + 2) ≤ 4 * l ^ 2 + 2 := by
    rcases Nat.eq_zero_or_pos l with rfl | hl
    · simp
    · have h3 : 2 * (l - 1) + 2 = 2 * l := by omega
      rw [h3]
      exact le_of_eq (by ring)
  exact h.trans h2

end M3
