/-
  M3 (F5): the conditional pencil lemma. Paper Lemma 4.1 ("Pencil
  families of orthogoval projective planes"), formalized CONDITIONALLY,
  mirroring how the paper cites CIJSSS arXiv:2210.11961 Theorem 2.2:
  the abstract hypothesis class `OrthogovalPair` packages exactly what
  the cited theorem provides (two projective planes of order q on a
  common point set, no shared line, cross intersections ≤ 2), and the
  pencil family of a pair is an I3-admissible(2q+2, 2) family of
  cardinality q²+q+1. Doubling (F1) then yields the paper's M3 lower
  bound. The all-prime-powers EXISTENCE of orthogoval pairs remains
  cited, not formalized; non-vacuity of the hypothesis class is
  decide-certified at q = 2 (a line-disjoint pair of Fano planes from
  the perfect difference sets {0,1,3} and {0,2,3} mod 7 — at q = 2 the
  cross condition is automatic since distinct 3-sets meet in ≤ 2).

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.M3.SmallValues

namespace M3

/-- An orthogoval pair of order `q`: two projective-plane line systems
    on a common point set, sharing no line, with cross intersections of
    size at most 2 (orthogovality). Lines are point sets; the
    projective-plane content used is packaged as: every point has
    pencil degree q+1 in each plane, and two distinct points lie on
    exactly one common line per plane. -/
structure OrthogovalPair (P : Type*) [DecidableEq P] [Fintype P]
    (q : ℕ) where
  lines₁ : Finset (Finset P)
  lines₂ : Finset (Finset P)
  point_count : Fintype.card P = q ^ 2 + q + 1
  degree₁ : ∀ p : P, (lines₁.filter (fun L => p ∈ L)).card = q + 1
  degree₂ : ∀ p : P, (lines₂.filter (fun L => p ∈ L)).card = q + 1
  unique₁ : ∀ p p' : P, p ≠ p' →
    ∃! L : Finset P, L ∈ lines₁ ∧ p ∈ L ∧ p' ∈ L
  unique₂ : ∀ p p' : P, p ≠ p' →
    ∃! L : Finset P, L ∈ lines₂ ∧ p ∈ L ∧ p' ∈ L
  no_shared : ∀ L ∈ lines₁, L ∉ lines₂
  cross : ∀ L₁ ∈ lines₁, ∀ L₂ ∈ lines₂, (L₁ ∩ L₂).card ≤ 2

variable {P : Type*} [DecidableEq P] [Fintype P] {q : ℕ}

/-- The pencil at a point: all lines of either plane through it. -/
def pencilAt (O : OrthogovalPair P q) (p : P) : Finset (Finset P) :=
  O.lines₁.filter (fun L => p ∈ L) ∪ O.lines₂.filter (fun L => p ∈ L)

/-- The pencil family: one pencil per point. -/
def pencilFam (O : OrthogovalPair P q) : Finset (Finset (Finset P)) :=
  Finset.univ.image (fun p => pencilAt O p)

lemma mem_pencilAt {O : OrthogovalPair P q} {p : P} {L : Finset P} :
    L ∈ pencilAt O p ↔
      (L ∈ O.lines₁ ∧ p ∈ L) ∨ (L ∈ O.lines₂ ∧ p ∈ L) := by
  simp [pencilAt, Finset.mem_union, Finset.mem_filter]

/-- Sizes: each pencil has 2(q+1) lines (the two through-p pencils are
    disjoint because the planes share no line). -/
lemma pencilAt_card (O : OrthogovalPair P q) (p : P) :
    (pencilAt O p).card = 2 * q + 2 := by
  rw [pencilAt, Finset.card_union_of_disjoint, O.degree₁ p, O.degree₂ p]
  · ring
  · rw [Finset.disjoint_left]
    intro L hL1 hL2
    exact O.no_shared L (Finset.mem_filter.mp hL1).1
      (Finset.mem_filter.mp hL2).1

/-- Pairwise intersections: the pencils of two distinct points meet in
    exactly the two connecting lines, one per plane, and those two lines
    meet in exactly the two points (orthogovality). -/
lemma pencil_inter (O : OrthogovalPair P q) {p p' : P} (hpp : p ≠ p') :
    ∃ U₁ U₂ : Finset P, U₁ ∈ O.lines₁ ∧ U₂ ∈ O.lines₂ ∧
      pencilAt O p ∩ pencilAt O p' = {U₁, U₂} ∧
      U₁ ∩ U₂ = {p, p'} := by
  obtain ⟨U₁, ⟨hU₁m, hpU₁, hp'U₁⟩, hU₁u⟩ := O.unique₁ p p' hpp
  obtain ⟨U₂, ⟨hU₂m, hpU₂, hp'U₂⟩, hU₂u⟩ := O.unique₂ p p' hpp
  refine ⟨U₁, U₂, hU₁m, hU₂m, ?_, ?_⟩
  · ext L
    simp only [Finset.mem_inter, mem_pencilAt, Finset.mem_insert,
      Finset.mem_singleton]
    constructor
    · rintro ⟨h1 | h1, h2 | h2⟩
      · exact Or.inl (hU₁u L ⟨h1.1, h1.2, h2.2⟩)
      · exact absurd h1.1 (fun hm => O.no_shared L hm h2.1)
      · exact absurd h2.1 (fun hm => O.no_shared L hm h1.1)
      · exact Or.inr (hU₂u L ⟨h1.1, h1.2, h2.2⟩)
    · rintro (rfl | rfl)
      · exact ⟨Or.inl ⟨hU₁m, hpU₁⟩, Or.inl ⟨hU₁m, hp'U₁⟩⟩
      · exact ⟨Or.inr ⟨hU₂m, hpU₂⟩, Or.inr ⟨hU₂m, hp'U₂⟩⟩
  · refine (Finset.eq_of_subset_of_card_le ?_ ?_).symm
    · intro x hx
      rw [Finset.mem_insert, Finset.mem_singleton] at hx
      rcases hx with rfl | rfl
      · exact Finset.mem_inter.mpr ⟨hpU₁, hpU₂⟩
      · exact Finset.mem_inter.mpr ⟨hp'U₁, hp'U₂⟩
    · calc (U₁ ∩ U₂).card ≤ 2 := O.cross U₁ hU₁m U₂ hU₂m
        _ = ({p, p'} : Finset P).card := by
            rw [Finset.card_insert_of_notMem (by
              rw [Finset.mem_singleton]; exact hpp),
              Finset.card_singleton]

/-- F5b: the pencil family is I3-admissible(2q+2, 2). -/
theorem pencilFam_I3Admissible (O : OrthogovalPair P q) :
    I3Admissible (pencilFam O) (2 * q + 2) 2 := by
  have hmem : ∀ X ∈ pencilFam O, ∃ p : P, pencilAt O p = X := by
    intro X hX
    obtain ⟨p, _, hp⟩ := Finset.mem_image.mp hX
    exact ⟨p, hp⟩
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · -- uniform
    intro X hX
    obtain ⟨p, rfl⟩ := hmem X hX
    exact pencilAt_card O p
  · -- capped at 2
    intro X hX Y hY hXY
    obtain ⟨a, rfl⟩ := hmem X hX
    obtain ⟨b, rfl⟩ := hmem Y hY
    have hab : a ≠ b := fun h => hXY (by rw [h])
    obtain ⟨U₁, U₂, _, _, hinter, _⟩ := pencil_inter O hab
    rw [hinter]
    exact le_trans (Finset.card_insert_le _ _) (by simp)
  · -- sunflower-free, by key uniqueness
    rintro H hH ⟨hcard, core, hcore⟩
    obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
    have hXm : X ∈ pencilFam O := hH (by simp)
    have hYm : Y ∈ pencilFam O := hH (by simp)
    have hZm : Z ∈ pencilFam O := hH (by simp)
    obtain ⟨a, rfl⟩ := hmem X hXm
    obtain ⟨b, rfl⟩ := hmem Y hYm
    obtain ⟨c, rfl⟩ := hmem Z hZm
    have hab : a ≠ b := fun h => hXY (by rw [h])
    have hac : a ≠ c := fun h => hXZ (by rw [h])
    obtain ⟨U₁, U₂, hU₁m, hU₂m, hUinter, hUpts⟩ := pencil_inter O hab
    obtain ⟨V₁, V₂, hV₁m, hV₂m, hVinter, hVpts⟩ := pencil_inter O hac
    have hcores : ({U₁, U₂} : Finset (Finset P)) = {V₁, V₂} := by
      rw [← hUinter, ← hVinter]
      rw [hcore _ _ (by simp) (by simp) hXY,
        hcore _ _ (by simp) (by simp) hXZ]
    -- plane separation: U₁ = V₁ and U₂ = V₂
    have hU₁V : U₁ = V₁ := by
      have h1 : U₁ ∈ ({V₁, V₂} : Finset (Finset P)) := by
        rw [← hcores]; simp
      rw [Finset.mem_insert, Finset.mem_singleton] at h1
      rcases h1 with h | h
      · exact h
      · subst h
        exact absurd hV₂m (O.no_shared _ hU₁m)
    have hU₂V : U₂ = V₂ := by
      have h1 : U₂ ∈ ({V₁, V₂} : Finset (Finset P)) := by
        rw [← hcores]; simp
      rw [Finset.mem_insert, Finset.mem_singleton] at h1
      rcases h1 with h | h
      · subst h
        exact absurd hU₂m (O.no_shared _ hV₁m)
      · exact h
    -- so {a, b} = U₁ ∩ U₂ = V₁ ∩ V₂ = {a, c}, forcing b = c
    have hpts : ({a, b} : Finset P) = {a, c} := by
      rw [← hUpts, hU₁V, hU₂V, hVpts]
    have hbc : b = c := by
      have hb : b ∈ ({a, c} : Finset P) := by
        rw [← hpts]; simp
      rw [Finset.mem_insert, Finset.mem_singleton] at hb
      rcases hb with h | h
      · exact absurd h.symm hab
      · exact h
    exact hYZ (by rw [hbc])
  · -- intersecting
    intro X hX Y hY hXY
    obtain ⟨a, rfl⟩ := hmem X hX
    obtain ⟨b, rfl⟩ := hmem Y hY
    have hab : a ≠ b := fun h => hXY (by rw [h])
    obtain ⟨U₁, U₂, _, _, hinter, _⟩ := pencil_inter O hab
    rw [hinter]
    exact ⟨U₁, by simp⟩

/-- The pencil map is injective for `q ≥ 1` (two pencils of distinct
    points share exactly 2 < 2q+2 lines). -/
lemma pencilAt_injective (O : OrthogovalPair P q) (hq : 1 ≤ q) :
    Function.Injective (pencilAt O) := by
  intro a b h
  by_contra hab
  obtain ⟨U₁, U₂, hU₁m, hU₂m, hinter, _⟩ := pencil_inter O hab
  have hcard2 : (pencilAt O a).card ≤ 2 := by
    rw [show pencilAt O a = pencilAt O a ∩ pencilAt O b from by
      rw [← h, Finset.inter_self], hinter]
    exact le_trans (Finset.card_insert_le _ _) (by simp)
  rw [pencilAt_card O a] at hcard2
  omega

/-- F5b, cardinality: the pencil family has q²+q+1 members. -/
theorem pencilFam_card (O : OrthogovalPair P q) (hq : 1 ≤ q) :
    (pencilFam O).card = q ^ 2 + q + 1 := by
  rw [pencilFam, Finset.card_image_of_injective _ (pencilAt_injective O hq),
    Finset.card_univ, O.point_count]

/-- F5c: doubling the pencil family — the paper's lower-bound mechanism,
    modulo the cited existence of orthogoval pairs (CIJSSS Thm 2.2). -/
theorem doubled_pencilFam (O : OrthogovalPair P q) (hq : 1 ≤ q) :
    ∃ H : Finset (Finset (Finset P ⊕ Finset P)),
      M3Admissible H (2 * q + 2) 2 ∧ H.card = 2 * (q ^ 2 + q + 1) := by
  obtain ⟨H, hadm, hcard⟩ := M3_ge_two_I3 (pencilFam O) (2 * q + 2) 2
    (by omega) (pencilFam_I3Admissible O)
  exact ⟨H, hadm, by rw [hcard, pencilFam_card O hq]⟩

/-
  F5d: non-vacuity at q = 2. Two Fano planes on Fin 7 from the perfect
  difference sets {0,1,3} and {0,2,3} mod 7. They share no line, and at
  q = 2 orthogovality is automatic (distinct 3-sets meet in ≤ 2 points).
-/

def fano1 : Finset (Finset (Fin 7)) :=
  { {0, 1, 3}, {1, 2, 4}, {2, 3, 5}, {3, 4, 6}, {0, 4, 5}, {1, 5, 6},
    {0, 2, 6} }

def fano2 : Finset (Finset (Fin 7)) :=
  { {0, 2, 3}, {1, 3, 4}, {2, 4, 5}, {3, 5, 6}, {0, 4, 6}, {0, 1, 5},
    {1, 2, 6} }

set_option maxRecDepth 8192 in
/-- F5d: the hypothesis class is non-vacuous — an explicit orthogoval
    pair of order 2, every field kernel-decided. -/
def fanoOrthogovalPair : OrthogovalPair (Fin 7) 2 where
  lines₁ := fano1
  lines₂ := fano2
  point_count := by decide
  degree₁ := by decide
  degree₂ := by decide
  unique₁ := by unfold ExistsUnique; decide
  unique₂ := by unfold ExistsUnique; decide
  no_shared := by decide
  cross := by decide

/-- F5d corollary: a concrete I3-admissible(6, 2) family of 7 pencils. -/
theorem fano_pencilFam_card : (pencilFam fanoOrthogovalPair).card = 7 :=
  pencilFam_card fanoOrthogovalPair (by norm_num)

end M3
