/-
  M3 (F4a): support relabeling. Any family of m l-sets has support of
  size at most m*l, and admissibility (M3 or I3) transports along any
  map injective on the support. Hence an upper bound "every admissible
  family over Fin ((v+1)*l) has at most v members" certifies the same
  bound over EVERY ground type: an offending family of v+1 members
  would relabel into Fin ((v+1)*l). This is the soundness lemma that
  lets SAT/decide results over a fixed Fin type certify M3/I3 values.

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.M3.LinkRecursion

namespace M3

variable {α : Type*} [DecidableEq α] {β : Type*} [DecidableEq β]

/-- Intersections commute with images under a map injective on the
    family's support. -/
lemma image_inter_of_injOn_support {F : Finset (Finset α)} {f : α → β}
    (hf : Set.InjOn f (F.biUnion id)) {S T : Finset α}
    (hS : S ∈ F) (hT : T ∈ F) :
    (S.image f) ∩ (T.image f) = (S ∩ T).image f := by
  have hSU : S ⊆ F.biUnion id := fun a ha =>
    Finset.mem_biUnion.mpr ⟨S, hS, ha⟩
  have hTU : T ⊆ F.biUnion id := fun a ha =>
    Finset.mem_biUnion.mpr ⟨T, hT, ha⟩
  ext y
  simp only [Finset.mem_inter, Finset.mem_image]
  constructor
  · rintro ⟨⟨a, ha, rfl⟩, ⟨b, hb, hba⟩⟩
    have hab : b = a := hf (hTU hb) (hSU ha) hba
    subst hab
    exact ⟨b, ⟨ha, hb⟩, rfl⟩
  · rintro ⟨a, ⟨ha, hb⟩, rfl⟩
    exact ⟨⟨a, ha, rfl⟩, ⟨a, hb, rfl⟩⟩

omit [DecidableEq α] in
/-- Images under a map injective on a common superset cancel. -/
lemma image_cancel_of_injOn {U : Finset α} {f : α → β}
    (hf : Set.InjOn f U) {P Q : Finset α}
    (hP : P ⊆ U) (hQ : Q ⊆ U) (h : P.image f = Q.image f) : P = Q := by
  have hsub : ∀ P' Q' : Finset α, P' ⊆ U → Q' ⊆ U →
      P'.image f = Q'.image f → P' ⊆ Q' := by
    intro P' Q' hP' hQ' h' a ha
    have hfa : f a ∈ Q'.image f := by
      rw [← h']; exact Finset.mem_image_of_mem f ha
    obtain ⟨b, hb, hba⟩ := Finset.mem_image.mp hfa
    have hab : b = a := hf (hQ' hb) (hP' ha) hba
    rwa [← hab]
  exact Finset.Subset.antisymm (hsub P Q hP hQ h) (hsub Q P hQ hP h.symm)

/-- F4a, transport: `M3`-admissibility moves along any map injective on
    the support, preserving cardinality. -/
theorem M3Admissible_image {F : Finset (Finset α)} {l t : ℕ} {f : α → β}
    (hF : M3Admissible F l t) (hf : Set.InjOn f (F.biUnion id)) :
    M3Admissible (F.image (fun S => S.image f)) l t ∧
      (F.image (fun S => S.image f)).card = F.card := by
  obtain ⟨hu, hc, hsf⟩ := hF
  have hSU : ∀ S ∈ F, S ⊆ F.biUnion id := fun S hS a ha =>
    Finset.mem_biUnion.mpr ⟨S, hS, ha⟩
  have hmem : ∀ X ∈ F.image (fun S => S.image f),
      ∃ S, S ∈ F ∧ S.image f = X := by
    intro X hX
    obtain ⟨S, hS, hSX⟩ := Finset.mem_image.mp hX
    exact ⟨S, hS, hSX⟩
  have hcancel : ∀ {P Q : Finset α}, P ∈ F → Q ∈ F →
      P.image f = Q.image f → P = Q := by
    intro P Q hP hQ h
    exact image_cancel_of_injOn hf (hSU P hP) (hSU Q hQ) h
  refine ⟨⟨?_, ?_, ?_⟩, ?_⟩
  · -- uniformity
    intro X hX
    obtain ⟨S, hSF, rfl⟩ := hmem X hX
    rw [Finset.card_image_of_injOn (hf.mono (Finset.coe_subset.mpr
      (hSU S hSF))), hu S hSF]
  · -- pairwise cap
    intro X hX Y hY hXY
    obtain ⟨S, hSF, rfl⟩ := hmem X hX
    obtain ⟨T, hTF, rfl⟩ := hmem Y hY
    have hST : S ≠ T := fun h => hXY (by rw [h])
    rw [image_inter_of_injOn_support hf hSF hTF,
      Finset.card_image_of_injOn (hf.mono (Finset.coe_subset.mpr
        ((Finset.inter_subset_left).trans (hSU S hSF))))]
    exact hc S hSF T hTF hST
  · -- sunflower-freeness
    rintro H hH ⟨hcard, core, hcore⟩
    obtain ⟨X, Y, Z, hXY, hXZ, hYZ, rfl⟩ := Finset.card_eq_three.mp hcard
    have hXm : X ∈ F.image (fun S => S.image f) := hH (by simp)
    have hYm : Y ∈ F.image (fun S => S.image f) := hH (by simp)
    have hZm : Z ∈ F.image (fun S => S.image f) := hH (by simp)
    obtain ⟨S, hSF, rfl⟩ := hmem X hXm
    obtain ⟨T, hTF, rfl⟩ := hmem Y hYm
    obtain ⟨W, hWF, rfl⟩ := hmem Z hZm
    have hST : S ≠ T := fun h => hXY (by rw [h])
    have hSW : S ≠ W := fun h => hXZ (by rw [h])
    have hTW : T ≠ W := fun h => hYZ (by rw [h])
    have eST : (S ∩ T).image f = core := by
      rw [← image_inter_of_injOn_support hf hSF hTF]
      exact hcore _ _ (by simp) (by simp) hXY
    have eSW : (S ∩ W).image f = core := by
      rw [← image_inter_of_injOn_support hf hSF hWF]
      exact hcore _ _ (by simp) (by simp) hXZ
    have eTW : (T ∩ W).image f = core := by
      rw [← image_inter_of_injOn_support hf hTF hWF]
      exact hcore _ _ (by simp) (by simp) hYZ
    have hsubST : S ∩ T ⊆ F.biUnion id :=
      (Finset.inter_subset_left).trans (hSU S hSF)
    have hsubSW : S ∩ W ⊆ F.biUnion id :=
      (Finset.inter_subset_left).trans (hSU S hSF)
    have hsubTW : T ∩ W ⊆ F.biUnion id :=
      (Finset.inter_subset_left).trans (hSU T hTF)
    have h1 : S ∩ T = S ∩ W :=
      image_cancel_of_injOn hf hsubST hsubSW (eST.trans eSW.symm)
    have h2 : S ∩ T = T ∩ W :=
      image_cancel_of_injOn hf hsubST hsubTW (eST.trans eTW.symm)
    refine hsf {S, T, W} ?_ ⟨?_, S ∩ T, ?_⟩
    · intro V hV
      simp only [Finset.mem_insert, Finset.mem_singleton] at hV
      rcases hV with rfl | rfl | rfl <;> assumption
    · exact Finset.card_eq_three.mpr ⟨S, T, W, hST, hSW, hTW, rfl⟩
    · intro P Q hP hQ hPQ
      simp only [Finset.mem_insert, Finset.mem_singleton] at hP hQ
      rcases hP with rfl | rfl | rfl <;> rcases hQ with rfl | rfl | rfl
      · exact absurd rfl hPQ
      · rfl
      · exact h1.symm
      · rw [Finset.inter_comm]
      · exact absurd rfl hPQ
      · exact h2.symm
      · rw [Finset.inter_comm]; exact h1.symm
      · rw [Finset.inter_comm]; exact h2.symm
      · exact absurd rfl hPQ
  · -- cardinality
    refine Finset.card_image_of_injOn ?_
    intro S hS T hT h
    rw [Finset.mem_coe] at hS hT
    have h' : S.image f = T.image f := h
    exact hcancel hS hT h'

/-- F4a, transport, intersecting variant. -/
theorem I3Admissible_image {F : Finset (Finset α)} {l t : ℕ} {f : α → β}
    (hF : I3Admissible F l t) (hf : Set.InjOn f (F.biUnion id)) :
    I3Admissible (F.image (fun S => S.image f)) l t ∧
      (F.image (fun S => S.image f)).card = F.card := by
  obtain ⟨hM, hcard⟩ := M3Admissible_image hF.1 hf
  refine ⟨⟨hM, ?_⟩, hcard⟩
  intro X hX Y hY hXY
  obtain ⟨S, hS, hSX⟩ := Finset.mem_image.mp hX
  obtain ⟨T, hT, hTY⟩ := Finset.mem_image.mp hY
  have hSX' : S.image f = X := hSX
  have hTY' : T.image f = Y := hTY
  subst hSX'; subst hTY'
  have hST : S ≠ T := fun h => hXY (by rw [h])
  rw [image_inter_of_injOn_support hf hS hT]
  exact (hF.2 S hS T hT hST).image f

/-- The support of `m` `l`-sets has at most `m*l` points. -/
lemma support_card_le {F : Finset (Finset α)} {l : ℕ}
    (hu : IsUniform F l) : (F.biUnion id).card ≤ F.card * l := by
  calc (F.biUnion id).card ≤ ∑ S ∈ F, (id S).card := Finset.card_biUnion_le
    _ = ∑ _S ∈ F, l := Finset.sum_congr rfl (fun S hS => hu S hS)
    _ = F.card * l := by rw [Finset.sum_const, smul_eq_mul]

omit [DecidableEq α] in
/-- A finset of size at most `n` (with `n > 0`) admits a map to `Fin n`
    injective on it. -/
lemma exists_injOn_fin {U : Finset α} {n : ℕ} (hn : 0 < n)
    (hU : U.card ≤ n) : ∃ f : α → Fin n, Set.InjOn f ↑U := by
  classical
  refine ⟨fun a => if h : a ∈ U then Fin.castLE hU (U.equivFin ⟨a, h⟩)
    else ⟨0, hn⟩, ?_⟩
  intro a ha b hb hab
  rw [Finset.mem_coe] at ha hb
  simp only [dif_pos ha, dif_pos hb] at hab
  have h1 := Fin.castLE_injective hU hab
  have h2 := U.equivFin.injective h1
  exact Subtype.mk.injEq .. ▸ h2

/-- F4a: a `Fin ((v+1)*l)` upper bound certifies the universal `M3`
    upper bound (`l > 0`; `l = 0` is `M3_card_le_t0` territory). -/
theorem M3_upper_of_fin {l t v : ℕ} (hl : 0 < l)
    (hub : ∀ G : Finset (Finset (Fin ((v + 1) * l))),
      M3Admissible G l t → G.card ≤ v)
    {γ : Type*} [DecidableEq γ] {F : Finset (Finset γ)}
    (hF : M3Admissible F l t) : F.card ≤ v := by
  by_contra h
  push_neg at h
  obtain ⟨F', hF'sub, hF'card⟩ : ∃ F' ⊆ F, F'.card = v + 1 :=
    Finset.exists_subset_card_eq (by omega)
  have hF' : M3Admissible F' l t := M3Admissible.subset hF hF'sub
  have hUcard : (F'.biUnion id).card ≤ (v + 1) * l := by
    have := support_card_le hF'.1
    rwa [hF'card] at this
  obtain ⟨f, hf⟩ := exists_injOn_fin (Nat.mul_pos (by omega) hl) hUcard
  obtain ⟨hadm, hcard⟩ := M3Admissible_image hF' hf
  have := hub _ hadm
  rw [hcard, hF'card] at this
  omega

/-- F4a: same certification for the intersecting quantity `I3`. -/
theorem I3_upper_of_fin {l t v : ℕ} (hl : 0 < l)
    (hub : ∀ G : Finset (Finset (Fin ((v + 1) * l))),
      I3Admissible G l t → G.card ≤ v)
    {γ : Type*} [DecidableEq γ] {F : Finset (Finset γ)}
    (hF : I3Admissible F l t) : F.card ≤ v := by
  by_contra h
  push_neg at h
  obtain ⟨F', hF'sub, hF'card⟩ : ∃ F' ⊆ F, F'.card = v + 1 :=
    Finset.exists_subset_card_eq (by omega)
  have hF' : I3Admissible F' l t :=
    ⟨M3Admissible.subset hF.1 hF'sub,
     fun S hS T hT hST => hF.2 S (hF'sub hS) T (hF'sub hT) hST⟩
  have hUcard : (F'.biUnion id).card ≤ (v + 1) * l := by
    have := support_card_le hF'.1.1
    rwa [hF'card] at this
  obtain ⟨f, hf⟩ := exists_injOn_fin (Nat.mul_pos (by omega) hl) hUcard
  obtain ⟨hadm, hcard⟩ := I3Admissible_image hF' hf
  have := hub _ hadm
  rw [hcard, hF'card] at this
  omega

end M3
