/-
  M3 (F4b): SAT encoding for M3(l,t)/I3(l,t) upper bounds — the encoder
  extension of the existing M(n,3) bridge (SunflowerLean/SATBridge.lean).

  ENCODING (documented per MASTER_PLAN_TO_DONE.md F4b):
  - Primary variables 0 .. 2^n - 1: one per subset of Fin n, by bitmask
    (variable m is true iff the subset `bitmaskToSubset n m` is in the
    family). Identical to the M(n,3) bridge.
  - `nonUniformClauses n l`: unit clause ¬x_m for every bitmask m whose
    subset does NOT have exactly l elements (uniformity).
  - `capViolationClauses n t`: binary clause ¬x_a ∨ ¬x_b for every pair
    a < b of bitmasks whose subsets are distinct and meet in MORE than t
    points (pairwise cap).
  - `disjointPairClauses n`: binary clause ¬x_a ∨ ¬x_b for every pair
    a < b of bitmasks whose subsets are distinct and disjoint
    (intersecting variant, I3).
  - `sunflowerClauses n` and `seqCounterClauses (2^n) B (2^n)` are reused
    verbatim from the M(n,3) bridge (3-sunflower exclusion; "at least B
    primary variables true" via the sequential counter on auxiliary
    variables 2^n ..).
  - `m3CNF n l t B` / `i3CNF n l t B`: the full encodings of "does a
    B-member M3(l,t)- / I3(l,t)-admissible family on Fin n exist?".

  The pair generators carry the subset-distinctness test INSIDE the
  generation condition, so the soundness lemmas below never need
  bitmask-injectivity: a generated clause hands us A ≠ B directly.

  SOUNDNESS (the only direction used): if the CNF is UNSAT then no
  B-member admissible family exists on Fin n (`m3_bridge`, `i3_bridge`).
  Combined with the relabel certifiers (M3/Relabel.lean, F4a), an UNSAT
  certificate over Fin ((v+1)*l) bounds M3/I3 over every ground type.

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.SATBridge
import SunflowerLean.M3.Relabel

open Std.Sat
open SunflowerLean

namespace M3

-- ============================================================================
-- Clause generators
-- ============================================================================

/-- Unit clauses excluding every subset that is not an `l`-set. -/
def nonUniformClauses (n l : Nat) : CNF Nat :=
  ((List.range (2 ^ n)).filter
    (fun m => (bitmaskToSubset n m).card ≠ l)).map
    (fun m => [(m, false)])

/-- Binary clauses excluding every distinct pair meeting in more than
    `t` points. -/
def capViolationClauses (n t : Nat) : CNF Nat :=
  (List.range (2 ^ n)).flatMap fun a =>
    (List.range (2 ^ n)).filterMap fun b =>
      if a < b ∧ bitmaskToSubset n a ≠ bitmaskToSubset n b ∧
          t < ((bitmaskToSubset n a) ∩ (bitmaskToSubset n b)).card then
        some [(a, false), (b, false)]
      else none

/-- Binary clauses excluding every distinct disjoint pair
    (intersecting variant). -/
def disjointPairClauses (n : Nat) : CNF Nat :=
  (List.range (2 ^ n)).flatMap fun a =>
    (List.range (2 ^ n)).filterMap fun b =>
      if a < b ∧ bitmaskToSubset n a ≠ bitmaskToSubset n b ∧
          (bitmaskToSubset n a) ∩ (bitmaskToSubset n b) = ∅ then
        some [(a, false), (b, false)]
      else none

/-- CNF: "does a `B`-member `M3(l,t)`-admissible family on `Fin n`
    exist?" UNSAT certifies `M3 < B` on `Fin n`. -/
def m3CNF (n l t B : Nat) : CNF Nat :=
  nonUniformClauses n l ++ capViolationClauses n t ++
    sunflowerClauses n ++ seqCounterClauses (2 ^ n) B (2 ^ n)

/-- CNF: the intersecting variant. UNSAT certifies `I3 < B` on `Fin n`. -/
def i3CNF (n l t B : Nat) : CNF Nat :=
  disjointPairClauses n ++ m3CNF n l t B

-- ============================================================================
-- Membership specifications
-- ============================================================================

lemma nonUniformClauses_spec {n l : Nat} {cl : CNF.Clause Nat}
    (h : cl ∈ nonUniformClauses n l) :
    ∃ m, m < 2 ^ n ∧ (bitmaskToSubset n m).card ≠ l ∧ cl = [(m, false)] := by
  simp only [nonUniformClauses, List.mem_map, List.mem_filter,
    List.mem_range] at h
  obtain ⟨m, ⟨hm, hcard⟩, rfl⟩ := h
  exact ⟨m, hm, by simpa using hcard, rfl⟩

lemma capViolationClauses_spec {n t : Nat} {cl : CNF.Clause Nat}
    (h : cl ∈ capViolationClauses n t) :
    ∃ a b, a < 2 ^ n ∧ b < 2 ^ n ∧
      bitmaskToSubset n a ≠ bitmaskToSubset n b ∧
      t < ((bitmaskToSubset n a) ∩ (bitmaskToSubset n b)).card ∧
      cl = [(a, false), (b, false)] := by
  simp only [capViolationClauses, List.mem_flatMap, List.mem_filterMap,
    List.mem_range] at h
  obtain ⟨a, ha, b, hb, hsome⟩ := h
  split at hsome
  · next hcond =>
    obtain ⟨_, hne, hcard⟩ := hcond
    exact ⟨a, b, ha, hb, hne, hcard, (Option.some.inj hsome).symm⟩
  · next => simp at hsome

lemma disjointPairClauses_spec {n : Nat} {cl : CNF.Clause Nat}
    (h : cl ∈ disjointPairClauses n) :
    ∃ a b, a < 2 ^ n ∧ b < 2 ^ n ∧
      bitmaskToSubset n a ≠ bitmaskToSubset n b ∧
      (bitmaskToSubset n a) ∩ (bitmaskToSubset n b) = ∅ ∧
      cl = [(a, false), (b, false)] := by
  simp only [disjointPairClauses, List.mem_flatMap, List.mem_filterMap,
    List.mem_range] at h
  obtain ⟨a, ha, b, hb, hsome⟩ := h
  split at hsome
  · next hcond =>
    obtain ⟨_, hne, hdisj⟩ := hcond
    exact ⟨a, b, ha, hb, hne, hdisj, (Option.some.inj hsome).symm⟩
  · next => simp at hsome

-- ============================================================================
-- Satisfaction by admissible families
-- ============================================================================

lemma uniform_satisfies_clauses {n l : Nat} {F : Finset (Finset (Fin n))}
    (hu : IsUniform F l) (σ : Nat → Bool)
    (hσ : ∀ i, σ i = decide (bitmaskToSubset n i ∈ F)) :
    ∀ cl ∈ nonUniformClauses n l, CNF.Clause.eval σ cl = true := by
  intro cl hcl
  obtain ⟨m, _, hcard, rfl⟩ := nonUniformClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  have hm : σ m = false := by
    rw [hσ m, decide_eq_false_iff_not]
    intro hmem
    exact hcard (hu _ hmem)
  rw [hm]
  rfl

lemma capped_satisfies_clauses {n t : Nat} {F : Finset (Finset (Fin n))}
    (hc : PairwiseCapped F t) (σ : Nat → Bool)
    (hσ : ∀ i, σ i = decide (bitmaskToSubset n i ∈ F)) :
    ∀ cl ∈ capViolationClauses n t, CNF.Clause.eval σ cl = true := by
  intro cl hcl
  obtain ⟨a, b, _, _, hne, hcard, rfl⟩ := capViolationClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  by_cases hA : bitmaskToSubset n a ∈ F
  · by_cases hB : bitmaskToSubset n b ∈ F
    · exfalso
      have := hc _ hA _ hB hne
      omega
    · have hb : σ b = false := by
        rw [hσ b, decide_eq_false_iff_not]; exact hB
      rw [hb]
      simp
  · have ha : σ a = false := by
      rw [hσ a, decide_eq_false_iff_not]; exact hA
    rw [ha]
    simp

lemma intersecting_satisfies_clauses {n : Nat} {F : Finset (Finset (Fin n))}
    (hint : IsIntersectingFam F) (σ : Nat → Bool)
    (hσ : ∀ i, σ i = decide (bitmaskToSubset n i ∈ F)) :
    ∀ cl ∈ disjointPairClauses n, CNF.Clause.eval σ cl = true := by
  intro cl hcl
  obtain ⟨a, b, _, _, hne, hdisj, rfl⟩ := disjointPairClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  by_cases hA : bitmaskToSubset n a ∈ F
  · by_cases hB : bitmaskToSubset n b ∈ F
    · exfalso
      have := hint _ hA _ hB hne
      rw [hdisj] at this
      exact Finset.not_nonempty_empty this
    · have hb : σ b = false := by
        rw [hσ b, decide_eq_false_iff_not]; exact hB
      rw [hb]
      simp
  · have ha : σ a = false := by
      rw [hσ a, decide_eq_false_iff_not]; exact hA
    rw [ha]
    simp

-- ============================================================================
-- Canonical-extension invariance (all new clauses use primary variables)
-- ============================================================================

lemma uniform_clause_eval_canonical (n l B : Nat) (σ : Nat → Bool)
    (cl : CNF.Clause Nat) (hcl : cl ∈ nonUniformClauses n l) :
    CNF.Clause.eval (canonicalExtension σ (2 ^ n) B (2 ^ n)) cl =
      CNF.Clause.eval σ cl := by
  obtain ⟨m, hm, _, rfl⟩ := nonUniformClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  rw [canonicalExtension_primary σ (2 ^ n) B m hm]

lemma cap_clause_eval_canonical (n t B : Nat) (σ : Nat → Bool)
    (cl : CNF.Clause Nat) (hcl : cl ∈ capViolationClauses n t) :
    CNF.Clause.eval (canonicalExtension σ (2 ^ n) B (2 ^ n)) cl =
      CNF.Clause.eval σ cl := by
  obtain ⟨a, b, ha, hb, _, _, rfl⟩ := capViolationClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  rw [canonicalExtension_primary σ (2 ^ n) B a ha,
    canonicalExtension_primary σ (2 ^ n) B b hb]

lemma disjoint_clause_eval_canonical (n B : Nat) (σ : Nat → Bool)
    (cl : CNF.Clause Nat) (hcl : cl ∈ disjointPairClauses n) :
    CNF.Clause.eval (canonicalExtension σ (2 ^ n) B (2 ^ n)) cl =
      CNF.Clause.eval σ cl := by
  obtain ⟨a, b, ha, hb, _, _, rfl⟩ := disjointPairClauses_spec hcl
  simp only [CNF.Clause.eval, List.any_cons, List.any_nil, Bool.or_false]
  rw [canonicalExtension_primary σ (2 ^ n) B a ha,
    canonicalExtension_primary σ (2 ^ n) B b hb]

-- ============================================================================
-- Bridge theorems
-- ============================================================================

/-- An admissible family of at least `B` members satisfies `m3CNF` under
    the canonical assignment. -/
lemma m3CNF_eval_of_admissible {n l t B : Nat}
    {F : Finset (Finset (Fin n))} (hF : M3Admissible F l t)
    (hge : B ≤ F.card) :
    CNF.eval (canonicalExtension
      (fun i => decide (bitmaskToSubset n i ∈ F)) (2 ^ n) B (2 ^ n))
      (m3CNF n l t B) = true := by
  obtain ⟨hu, hc, hsf⟩ := hF
  set σ : Nat → Bool := fun i => decide (bitmaskToSubset n i ∈ F) with hσdef
  set σ' := canonicalExtension σ (2 ^ n) B (2 ^ n) with hσ'def
  change (nonUniformClauses n l ++ capViolationClauses n t ++
    sunflowerClauses n ++ seqCounterClauses (2 ^ n) B (2 ^ n)).all
    (fun c => CNF.Clause.eval σ' c) = true
  rw [List.all_append, List.all_append, List.all_append]
  simp only [Bool.and_eq_true]
  refine ⟨⟨⟨?_, ?_⟩, ?_⟩, ?_⟩
  · rw [List.all_eq_true]
    intro c hc'
    rw [hσ'def, uniform_clause_eval_canonical n l B σ c hc']
    exact uniform_satisfies_clauses hu σ (fun i => rfl) c hc'
  · rw [List.all_eq_true]
    intro c hc'
    rw [hσ'def, cap_clause_eval_canonical n t B σ c hc']
    exact capped_satisfies_clauses hc σ (fun i => rfl) c hc'
  · rw [List.all_eq_true]
    intro c hc'
    rw [hσ'def, sf_clause_eval_canonical n B σ c hc']
    exact sf_free_satisfies_clauses n F hsf σ (fun i => rfl) c hc'
  · rw [List.all_eq_true]
    intro c hc'
    have hcount := countFalse_from_card n B F hge σ (fun i => rfl)
    exact seqCounter_sound (2 ^ n) B (2 ^ n) σ hcount
      (by exact Nat.one_le_two_pow) rfl c hc'

/-- F4b bridge: if `m3CNF n l t B` is UNSAT then every `M3(l,t)`-
    admissible family on `Fin n` has fewer than `B` members. -/
theorem m3_bridge (n l t B : Nat)
    (hunsat : (m3CNF n l t B).Unsat) :
    ∀ F : Finset (Finset (Fin n)), M3Admissible F l t → F.card < B := by
  intro F hF
  by_contra hge
  push_neg at hge
  have hsat := m3CNF_eval_of_admissible hF hge
  have hfalse := hunsat (canonicalExtension
    (fun i => decide (bitmaskToSubset n i ∈ F)) (2 ^ n) B (2 ^ n))
  rw [hfalse] at hsat
  exact absurd hsat (by decide)

/-- An intersecting admissible family of at least `B` members satisfies
    `i3CNF` under the canonical assignment. -/
lemma i3CNF_eval_of_admissible {n l t B : Nat}
    {F : Finset (Finset (Fin n))} (hF : I3Admissible F l t)
    (hge : B ≤ F.card) :
    CNF.eval (canonicalExtension
      (fun i => decide (bitmaskToSubset n i ∈ F)) (2 ^ n) B (2 ^ n))
      (i3CNF n l t B) = true := by
  set σ : Nat → Bool := fun i => decide (bitmaskToSubset n i ∈ F) with hσdef
  set σ' := canonicalExtension σ (2 ^ n) B (2 ^ n) with hσ'def
  change (disjointPairClauses n ++ m3CNF n l t B).all
    (fun c => CNF.Clause.eval σ' c) = true
  rw [List.all_append]
  simp only [Bool.and_eq_true]
  constructor
  · rw [List.all_eq_true]
    intro c hc'
    rw [hσ'def, disjoint_clause_eval_canonical n B σ c hc']
    exact intersecting_satisfies_clauses hF.2 σ (fun i => rfl) c hc'
  · exact m3CNF_eval_of_admissible hF.1 hge

/-- F4b bridge, intersecting variant: if `i3CNF n l t B` is UNSAT then
    every `I3(l,t)`-admissible family on `Fin n` has fewer than `B`
    members. -/
theorem i3_bridge (n l t B : Nat)
    (hunsat : (i3CNF n l t B).Unsat) :
    ∀ F : Finset (Finset (Fin n)), I3Admissible F l t → F.card < B := by
  intro F hF
  by_contra hge
  push_neg at hge
  have hsat := i3CNF_eval_of_admissible hF hge
  have hfalse := hunsat (canonicalExtension
    (fun i => decide (bitmaskToSubset n i ∈ F)) (2 ^ n) B (2 ^ n))
  rw [hfalse] at hsat
  exact absurd hsat (by decide)

end M3
