/-
  M2 (F2): the exact t=1 theorem. This file grows sub-item by sub-item per
  MASTER_PLAN_TO_DONE.md (F2a-F2g), each kernel-gated before check-off.

  F2a (this increment): the degree lemma — in a 1-capped 3-sunflower-free
  family, no point lies in three members (their pairwise intersections
  would all equal that singleton: a sunflower). Paper Theorem 1.1, step (i).

  Authors: Cody Mitchell, Claude (Fable)
  Date: June 2026
  Provenance: candidates generated by Claude; acceptance criterion is
  `lake build` (kernel) + axiom audit; committed only if sorry-free.
-/

import SunflowerLean.M3.Doubling

namespace M3

variable {α : Type*} [DecidableEq α]

/-- In a 1-capped family, two distinct members through a common point meet
    in exactly that singleton. -/
lemma inter_eq_singleton_of_capped {F : Finset (Finset α)}
    (hc : PairwiseCapped F 1) {A B : Finset α} (hA : A ∈ F) (hB : B ∈ F)
    (hAB : A ≠ B) {x : α} (hxA : x ∈ A) (hxB : x ∈ B) :
    A ∩ B = {x} := by
  have hx : x ∈ A ∩ B := Finset.mem_inter.mpr ⟨hxA, hxB⟩
  have h1 : (A ∩ B).card = 1 :=
    le_antisymm (hc A hA B hB hAB) (Finset.one_le_card.mpr ⟨x, hx⟩)
  obtain ⟨y, hy⟩ := Finset.card_eq_one.mp h1
  rw [hy] at hx ⊢
  rw [Finset.mem_singleton] at hx
  rw [hx]

/-- F2a, core form: three distinct members of a 1-capped 3-sunflower-free
    family cannot share a point (they would form a sunflower with core
    that singleton). -/
lemma no_three_through_point {F : Finset (Finset α)}
    (hc : PairwiseCapped F 1) (hsf : IsSunflowerFree F 3) {x : α}
    {A B C : Finset α} (hA : A ∈ F) (hB : B ∈ F) (hC : C ∈ F)
    (hAB : A ≠ B) (hAC : A ≠ C) (hBC : B ≠ C)
    (hxA : x ∈ A) (hxB : x ∈ B) (hxC : x ∈ C) : False := by
  have eAB := inter_eq_singleton_of_capped hc hA hB hAB hxA hxB
  have eAC := inter_eq_singleton_of_capped hc hA hC hAC hxA hxC
  have eBC := inter_eq_singleton_of_capped hc hB hC hBC hxB hxC
  refine hsf {A, B, C} ?_ ⟨?_, {x}, ?_⟩
  · intro W hW
    simp only [Finset.mem_insert, Finset.mem_singleton] at hW
    rcases hW with rfl | rfl | rfl <;> assumption
  · exact Finset.card_eq_three.mpr ⟨A, B, C, hAB, hAC, hBC, rfl⟩
  · intro S T hS hT hST
    simp only [Finset.mem_insert, Finset.mem_singleton] at hS hT
    rcases hS with rfl | rfl | rfl <;> rcases hT with rfl | rfl | rfl
    · exact absurd rfl hST
    · exact eAB
    · exact eAC
    · rw [Finset.inter_comm]; exact eAB
    · exact absurd rfl hST
    · exact eBC
    · rw [Finset.inter_comm]; exact eAC
    · rw [Finset.inter_comm]; exact eBC
    · exact absurd rfl hST

/-- F2a, degree form: every point lies in at most two members of a
    1-capped 3-sunflower-free family. -/
lemma degree_le_two {F : Finset (Finset α)}
    (hc : PairwiseCapped F 1) (hsf : IsSunflowerFree F 3) (x : α) :
    (F.filter (fun S => x ∈ S)).card ≤ 2 := by
  by_contra h
  push_neg at h
  obtain ⟨T, hTsub, hTcard⟩ :
      ∃ T ⊆ F.filter (fun S => x ∈ S), T.card = 3 :=
    Finset.exists_subset_card_eq (by omega)
  obtain ⟨A, B, C, hAB, hAC, hBC, rfl⟩ := Finset.card_eq_three.mp hTcard
  have hAm : A ∈ F.filter (fun S => x ∈ S) :=
    hTsub (show A ∈ ({A, B, C} : Finset (Finset α)) by simp)
  have hBm : B ∈ F.filter (fun S => x ∈ S) :=
    hTsub (show B ∈ ({A, B, C} : Finset (Finset α)) by simp)
  have hCm : C ∈ F.filter (fun S => x ∈ S) :=
    hTsub (show C ∈ ({A, B, C} : Finset (Finset α)) by simp)
  obtain ⟨hA, hxA⟩ := Finset.mem_filter.mp hAm
  obtain ⟨hB, hxB⟩ := Finset.mem_filter.mp hBm
  obtain ⟨hC, hxC⟩ := Finset.mem_filter.mp hCm
  exact no_three_through_point hc hsf hA hB hC hAB hAC hBC hxA hxB hxC

end M3
